font_family DejaVu Sans Mono
font_size 11.0

foreground #E6E6E6
background #0B0C0F

cursor #00E6D0
cursor_shape block

selection_foreground #0B0C0F
selection_background #00E6D0

scrollback_lines 5000

window_padding_width 8
enable_audio_bell no

confirm_os_window_close 0

tab_bar_edge top
tab_bar_style powerline
