[mgr]
cwd = { fg = "#00E6D0" }

hovered = { fg = "#E6E6E6", bg = "#202328" }
preview_hovered = { fg = "#E6E6E6", bg = "#15171B" }

find_keyword = { fg = "#0B0C0F", bg = "#00E6D0", bold = true }
find_position = { fg = "#00E6D0", bold = true }

marker_copied = { fg = "#00E6D0", bg = "#00E6D0" }
marker_cut = { fg = "#E05252", bg = "#E05252" }
marker_marked = { fg = "#D4B45A", bg = "#D4B45A" }
marker_selected = { fg = "#00E6D0", bg = "#00E6D0" }

tab_active = { fg = "#0B0C0F", bg = "#00E6D0", bold = true }
tab_inactive = { fg = "#70757D", bg = "#15171B" }

count_copied = { fg = "#0B0C0F", bg = "#00E6D0" }
count_cut = { fg = "#FFFFFF", bg = "#E05252" }
count_selected = { fg = "#0B0C0F", bg = "#00E6D0" }

border_symbol = "│"
border_style = { fg = "#25282D" }

[status]
separator_open = ""
separator_close = ""

mode_normal = { fg = "#0B0C0F", bg = "#00E6D0", bold = true }
mode_select = { fg = "#0B0C0F", bg = "#D4B45A", bold = true }
mode_unset = { fg = "#0B0C0F", bg = "#E05252", bold = true }

progress_label = { fg = "#E6E6E6", bold = true }
progress_normal = { fg = "#00E6D0", bg = "#25282D" }
progress_error = { fg = "#E05252", bg = "#25282D" }

perm_type = { fg = "#70757D" }
perm_read = { fg = "#66BB6A" }
perm_write = { fg = "#D4B45A" }
perm_exec = { fg = "#00E6D0" }
perm_sep = { fg = "#25282D" }

[mode]
normal_main = { fg = "#0B0C0F", bg = "#00E6D0", bold = true }
normal_alt = { fg = "#00E6D0", bg = "#15171B" }

select_main = { fg = "#0B0C0F", bg = "#D4B45A", bold = true }
select_alt = { fg = "#D4B45A", bg = "#15171B" }

unset_main = { fg = "#0B0C0F", bg = "#E05252", bold = true }
unset_alt = { fg = "#E05252", bg = "#15171B" }

[preview]
tab = { fg = "#00E6D0", bold = true }

[filetype]
rules = [
    { url = "*/", fg = "#00E6D0", bold = true },

    { mime = "image/*", fg = "#B77CFF" },
    { mime = "video/*", fg = "#E05252" },
    { mime = "audio/*", fg = "#D4B45A" },

    { mime = "application/zip", fg = "#D4B45A" },
    { mime = "application/x-tar", fg = "#D4B45A" },
    { mime = "application/x-gzip", fg = "#D4B45A" },

    { is = "exec", fg = "#00E6D0", bold = true },
    { is = "link", fg = "#76A7FF" },
    { is = "orphan", fg = "#E05252" },

    { url = "*", fg = "#E6E6E6" }
]
