#!/bin/sh

/usr/local/bin/vmtoolsd -n vmusr &

sxhkd &
sleep 1

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width 2
bspc config focused_border_color "#00ffcc"
bspc config normal_border_color "#202020"
bspc config presel_feedback_color "#00ffcc"

xsetroot -solid "#000000"

pkill dunst 2>/dev/null
dunst &

pkill picom 2>/dev/null
picom --config /dev/null -b --backend=xrender \
--shadow \
--shadow-radius=8 \
--shadow-offset-x=-4 \
--shadow-offset-y=-4 \
--inactive-opacity=0.92 \
--active-opacity=1.0

feh --bg-fill "$HOME/Pictures/Wallpapers/y2k.jpg" &

pkill polybar 2>/dev/null
polybar y2k &
